// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiV3i-YEKPx9Rxjd1UkdB6wp_FxhtvuxY',
    appId: '1:37188291553:web:52e0b56c29516e168f20a0',
    messagingSenderId: '37188291553',
    projectId: 'login-form-96c0e',
    authDomain: 'login-form-96c0e.firebaseapp.com',
    storageBucket: 'login-form-96c0e.appspot.com',
    measurementId: 'G-93E9VLHVYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQOBibHP282arlWN5-B86rZ7-ec5fzns',
    appId: '1:37188291553:android:5e44777292e613f38f20a0',
    messagingSenderId: '37188291553',
    projectId: 'login-form-96c0e',
    storageBucket: 'login-form-96c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBY2DH14o9sRF-PWwMXaKjzVJfJyK-GDs',
    appId: '1:37188291553:ios:c020cec03dd51fbd8f20a0',
    messagingSenderId: '37188291553',
    projectId: 'login-form-96c0e',
    storageBucket: 'login-form-96c0e.appspot.com',
    iosClientId: '37188291553-1hetofgugrdndbe76n8fn6ij281ebhmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBY2DH14o9sRF-PWwMXaKjzVJfJyK-GDs',
    appId: '1:37188291553:ios:c020cec03dd51fbd8f20a0',
    messagingSenderId: '37188291553',
    projectId: 'login-form-96c0e',
    storageBucket: 'login-form-96c0e.appspot.com',
    iosClientId: '37188291553-1hetofgugrdndbe76n8fn6ij281ebhmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
